import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dir: 'ltr',
    lang: 'en',
    nav: {
      home: 'Home', about: 'About', services: 'Services',
      categories: 'Categories', contact: 'Contact',
    },
    home: {
      badge: 'Odoo Gold Partner',
      h1a: 'Integrate.',
      h1b: 'Automate.',
      h1c: 'Scale.',
      sub: 'NETC is a leading Odoo integration specialist for enterprises. We deploy, customize, and optimize Odoo ERP to transform how your business operates.',
      cta_primary: 'Explore Services',
      cta_secondary: 'Contact Us',
      why_label: 'Why NETC',
      why_title: 'Built for Enterprise',
      why_desc: 'We combine deep Odoo expertise with enterprise-grade delivery to drive real business transformation.',
      features: [
        { title: 'Odoo Experts', desc: 'Certified Odoo specialists with deep module and customization expertise.' },
        { title: 'Enterprise-Grade', desc: 'Scalable, secure deployments built for complex business environments.' },
        { title: 'Fast Implementation', desc: 'Streamlined methodology that gets you live quickly without disruption.' },
        { title: 'Global Support', desc: 'Multilingual support teams available wherever your business operates.' },
      ],
      cat_label: 'Categories',
      cat_title: 'What We Offer',
      cat_desc: 'End-to-end Odoo solutions organized by business domain.',
      services_label: 'Featured',
      services_title: 'Our Services',
      services_desc: 'Premium Odoo solutions tailored to your enterprise needs.',
      view_all: 'View All Services',
      cta_title: 'Ready to transform your business?',
      cta_desc: "Let's build your Odoo ecosystem together. Talk to our experts today.",
      cta_btn: 'Start a Project',
    },
    about: {
      badge: 'About NETC',
      headline1: 'Your trusted partner',
      headline2: 'for Odoo',
      headline3: 'integration.',
      sub: 'NETC is a specialized Odoo integration firm serving enterprises across industries. We bring technical depth, business acumen, and a proven methodology to every deployment.',
      cta: 'Our Services',
      years: 'Years of Innovation',
      statsLabel: ['Projects Delivered', 'Happy Clients', 'Years Experience', 'Support'],
      valuesLabel: 'Our Values',
      valuesTitle: 'What Drives Us',
      valuesDesc: 'The principles that guide everything we do.',
      values: [
        { title: 'Precision', desc: 'Every integration is crafted with surgical accuracy and attention to detail.' },
        { title: 'Collaboration', desc: 'We work closely with your team to understand and exceed expectations.' },
        { title: 'Excellence', desc: 'We never settle for good enough — your ERP deserves the best.' },
        { title: 'Efficiency', desc: 'Time is valuable. We deliver on schedule, every time.' },
      ],
      cta_ready: 'Ready to get started?',
      cta_ready_desc: "Let's build your Odoo ecosystem together.",
      cta_btn: 'Start a Project',
    },
    services: {
      label: 'Services',
      title: 'What We Build',
      desc: 'Comprehensive Odoo integration and customization services for enterprises.',
      search: 'Search services...',
      all: 'All',
      dev: 'Development',
      nondev: 'Non-Development',
      allCats: 'All Categories',
      empty: 'No services match your criteria.',
      clear: 'Clear filters',
    },
    categories: {
      label: 'Categories',
      title: 'Browse by Category',
      desc: 'Find the right Odoo service for your business needs.',
      services_count: 'services',
    },
    contact: {
      label: 'Contact',
      title: "Let's talk about your Odoo project.",
      sub: 'Have an integration in mind? Fill out the form and our Odoo experts will get back to you within 24 hours.',
      email_label: 'Email',
      phone_label: 'Phone',
      location_label: 'Location',
      name_ph: 'Your name',
      email_ph: 'Your email',
      phone_ph: 'Phone number',
      interest_ph: 'Odoo module / service interested in',
      message_ph: 'Tell us about your project...',
      send: 'Send Message',
      sending: 'Sending...',
      success: "Message sent! We'll get back to you soon.",
    },
    footer: {
      rights: 'All rights reserved.',
    },
    theme: { dark: 'Dark', light: 'Light' },
  },

  fr: {
    dir: 'ltr',
    lang: 'fr',
    nav: {
      home: 'Accueil', about: 'À propos', services: 'Services',
      categories: 'Catégories', contact: 'Contact',
    },
    home: {
      badge: 'Partenaire Gold Odoo',
      h1a: 'Intégrer.',
      h1b: 'Automatiser.',
      h1c: 'Évoluer.',
      sub: "NETC est un spécialiste de l'intégration Odoo pour les entreprises. Nous déployons, personnalisons et optimisons Odoo ERP pour transformer vos opérations.",
      cta_primary: 'Voir nos services',
      cta_secondary: 'Nous contacter',
      why_label: 'Pourquoi NETC',
      why_title: "Conçu pour l'entreprise",
      why_desc: "Nous combinons une expertise Odoo approfondie avec une livraison de qualité entreprise pour une transformation réelle.",
      features: [
        { title: 'Experts Odoo', desc: 'Spécialistes Odoo certifiés avec une expertise approfondie en modules et personnalisations.' },
        { title: 'Qualité Entreprise', desc: 'Déploiements sécurisés et évolutifs pour des environnements complexes.' },
        { title: 'Mise en œuvre rapide', desc: 'Méthodologie rationalisée pour un lancement rapide sans perturbation.' },
        { title: 'Support Mondial', desc: 'Équipes de support multilingues disponibles partout dans le monde.' },
      ],
      cat_label: 'Catégories',
      cat_title: 'Ce que nous offrons',
      cat_desc: 'Solutions Odoo de bout en bout organisées par domaine métier.',
      services_label: 'À la une',
      services_title: 'Nos Services',
      services_desc: 'Solutions Odoo premium adaptées à vos besoins enterprise.',
      view_all: 'Voir tous les services',
      cta_title: 'Prêt à transformer votre entreprise ?',
      cta_desc: "Construisons votre écosystème Odoo ensemble. Parlez à nos experts dès aujourd'hui.",
      cta_btn: 'Démarrer un projet',
    },
    about: {
      badge: 'À propos de NETC',
      headline1: 'Votre partenaire de confiance',
      headline2: "pour l'intégration",
      headline3: 'Odoo.',
      sub: "NETC est une société spécialisée dans l'intégration Odoo pour les entreprises. Nous apportons expertise technique, sens des affaires et méthodologie éprouvée à chaque déploiement.",
      cta: 'Nos Services',
      years: "Ans d'Innovation",
      statsLabel: ['Projets Livrés', 'Clients Satisfaits', "Ans d'Expérience", 'Support'],
      valuesLabel: 'Nos Valeurs',
      valuesTitle: 'Ce qui nous motive',
      valuesDesc: 'Les principes qui guident tout ce que nous faisons.',
      values: [
        { title: 'Précision', desc: 'Chaque intégration est réalisée avec une précision chirurgicale.' },
        { title: 'Collaboration', desc: 'Nous travaillons étroitement avec votre équipe pour dépasser vos attentes.' },
        { title: 'Excellence', desc: "Nous ne nous contentons jamais du suffisant — votre ERP mérite le meilleur." },
        { title: 'Efficacité', desc: 'Le temps est précieux. Nous livrons dans les délais, à chaque fois.' },
      ],
      cta_ready: 'Prêt à commencer ?',
      cta_ready_desc: "Construisons votre écosystème Odoo ensemble.",
      cta_btn: 'Démarrer un projet',
    },
    services: {
      label: 'Services',
      title: 'Ce que nous faisons',
      desc: "Services complets d'intégration et de personnalisation Odoo pour les entreprises.",
      search: 'Rechercher des services...',
      all: 'Tous',
      dev: 'Développement',
      nondev: 'Non-Développement',
      allCats: 'Toutes les catégories',
      empty: 'Aucun service ne correspond à vos critères.',
      clear: 'Effacer les filtres',
    },
    categories: {
      label: 'Catégories',
      title: 'Parcourir par catégorie',
      desc: 'Trouvez le bon service Odoo pour vos besoins métier.',
      services_count: 'services',
    },
    contact: {
      label: 'Contact',
      title: 'Parlons de votre projet Odoo.',
      sub: "Vous avez une intégration en tête ? Remplissez le formulaire et nos experts Odoo vous répondront sous 24 heures.",
      email_label: 'Email',
      phone_label: 'Téléphone',
      location_label: 'Localisation',
      name_ph: 'Votre nom',
      email_ph: 'Votre email',
      phone_ph: 'Numéro de téléphone',
      interest_ph: 'Module Odoo / service souhaité',
      message_ph: 'Parlez-nous de votre projet...',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      success: "Message envoyé ! Nous vous répondrons bientôt.",
    },
    footer: {
      rights: 'Tous droits réservés.',
    },
    theme: { dark: 'Sombre', light: 'Clair' },
  },

  ar: {
    dir: 'rtl',
    lang: 'ar',
    nav: {
      home: 'الرئيسية', about: 'من نحن', services: 'الخدمات',
      categories: 'الفئات', contact: 'اتصل بنا',
    },
    home: {
      badge: 'شريك Odoo الذهبي',
      h1a: 'تكامل.',
      h1b: 'أتمتة.',
      h1c: 'توسّع.',
      sub: 'NETC شركة متخصصة في تكامل Odoo للمؤسسات. نقوم بنشر وتخصيص وتحسين نظام Odoo ERP لتحويل طريقة عمل مؤسستك.',
      cta_primary: 'استكشف الخدمات',
      cta_secondary: 'اتصل بنا',
      why_label: 'لماذا NETC',
      why_title: 'مصمم للمؤسسات',
      why_desc: 'نجمع بين خبرة Odoo العميقة وتسليم بمستوى المؤسسات لتحقيق تحول تجاري حقيقي.',
      features: [
        { title: 'خبراء Odoo', desc: 'متخصصون معتمدون في Odoo مع خبرة عميقة في الوحدات والتخصيصات.' },
        { title: 'مستوى مؤسسي', desc: 'نشر آمن وقابل للتوسع لبيئات الأعمال المعقدة.' },
        { title: 'تطبيق سريع', desc: 'منهجية مبسطة تُطلق مشروعك بسرعة دون انقطاع.' },
        { title: 'دعم عالمي', desc: 'فرق دعم متعددة اللغات في كل مكان تعمل فيه مؤسستك.' },
      ],
      cat_label: 'الفئات',
      cat_title: 'ما نقدمه',
      cat_desc: 'حلول Odoo متكاملة مرتبة حسب مجال الأعمال.',
      services_label: 'مميز',
      services_title: 'خدماتنا',
      services_desc: 'حلول Odoo متميزة مصممة لاحتياجات مؤسستك.',
      view_all: 'عرض جميع الخدمات',
      cta_title: 'هل أنت مستعد لتحويل مؤسستك؟',
      cta_desc: 'لنبني معاً منظومة Odoo الخاصة بك. تحدث إلى خبرائنا اليوم.',
      cta_btn: 'ابدأ مشروعك',
    },
    about: {
      badge: 'عن NETC',
      headline1: 'شريكك الموثوق',
      headline2: 'لتكامل',
      headline3: 'Odoo.',
      sub: 'NETC شركة متخصصة في تكامل Odoo للمؤسسات عبر مختلف الصناعات. نجلب الخبرة التقنية والفكر التجاري ومنهجية مُجرَّبة لكل عملية نشر.',
      cta: 'خدماتنا',
      years: 'سنوات من الابتكار',
      statsLabel: ['مشروع منجز', 'عميل سعيد', 'سنوات خبرة', 'دعم'],
      valuesLabel: 'قيمنا',
      valuesTitle: 'ما يحرّكنا',
      valuesDesc: 'المبادئ التي توجّه كل ما نقوم به.',
      values: [
        { title: 'الدقة', desc: 'كل تكامل يُنفَّذ بدقة جراحية واهتمام بكل تفصيل.' },
        { title: 'التعاون', desc: 'نعمل مع فريقك عن كثب لفهم توقعاتك وتجاوزها.' },
        { title: 'التميّز', desc: 'لا نقبل بأقل من الأفضل — نظام ERP الخاص بك يستحق ذلك.' },
        { title: 'الكفاءة', desc: 'الوقت ثمين. نُسلّم في الموعد، في كل مرة.' },
      ],
      cta_ready: 'مستعد للبدء؟',
      cta_ready_desc: 'لنبني معاً منظومة Odoo الخاصة بك.',
      cta_btn: 'ابدأ مشروعك',
    },
    services: {
      label: 'الخدمات',
      title: 'ما نقوم ببنائه',
      desc: 'خدمات شاملة لتكامل وتخصيص Odoo للمؤسسات.',
      search: 'ابحث عن الخدمات...',
      all: 'الكل',
      dev: 'تطوير',
      nondev: 'غير تقني',
      allCats: 'جميع الفئات',
      empty: 'لا توجد خدمات تطابق معاييرك.',
      clear: 'مسح الفلاتر',
    },
    categories: {
      label: 'الفئات',
      title: 'تصفح حسب الفئة',
      desc: 'ابحث عن خدمة Odoo المناسبة لاحتياجات مؤسستك.',
      services_count: 'خدمات',
    },
    contact: {
      label: 'اتصل بنا',
      title: 'لنتحدث عن مشروع Odoo الخاص بك.',
      sub: 'لديك مشروع تكامل في ذهنك؟ املأ النموذج وسيتواصل معك خبراؤنا خلال 24 ساعة.',
      email_label: 'البريد الإلكتروني',
      phone_label: 'الهاتف',
      location_label: 'الموقع',
      name_ph: 'اسمك',
      email_ph: 'بريدك الإلكتروني',
      phone_ph: 'رقم الهاتف',
      interest_ph: 'وحدة Odoo / الخدمة المطلوبة',
      message_ph: 'أخبرنا عن مشروعك...',
      send: 'إرسال الرسالة',
      sending: 'جارٍ الإرسال...',
      success: 'تم إرسال رسالتك! سنتواصل معك قريباً.',
    },
    footer: {
      rights: 'جميع الحقوق محفوظة.',
    },
    theme: { dark: 'داكن', light: 'فاتح' },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('netc_lang') || 'en');

  const t = translations[lang] || translations.en;

  useEffect(() => {
    localStorage.setItem('netc_lang', lang);
    document.documentElement.dir = t.dir;
    document.documentElement.lang = t.lang;
  }, [lang, t]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}